### ISSUE TITLE
Update for Endwalker?

### ISSUE THREAD

**Issue by El0quenz** [akira0245/SmartCast#4]
Hey,

I am a big fan of your Plugin and wanted to ask if you intend to update it for 6.0?
The Plugin was very helpful and I would love to use it again.

Great work and I hope you find the time to update it!

Regards

**Comment by akira0245** [comment]
The plugin has been updated with the help of @wozaiha, I pushed it to a new plugin `SmartCast(Endwalker)` because chinese users still need the old version. Thank you for liking my plugin!

**Comment by F-a-y-t-h** [comment]
The macro queue option doesn't seem to be working in the endwalker port; thank the update however~

ps. i hope there is plans to update Radar.

**Comment by El0quenz** [comment]
Awesome!! All the features work perfectly 👍 
Thank you so much for updating it and for the great work!

I love the Dismount and do action, super convenient!  :)) so happy!

**Comment by akira0245** [comment]
I assume there are no further concerns about the updates, so I'll close this issue.
