### ISSUE TITLE
Mouseover not working 

### ISSUE THREAD

**Issue by Yuikase** [akira0245/SmartCast#6]
It seems that mouseover function is currently not working

**Comment by akira0245** [comment]
yep, it should be fixed in #5

**Comment by Yuikase** [comment]
Thats wonderful news thanks for the update

**Comment by wozaiha** [comment]
> Thats wonderful news thanks for the update

UI hover is not working IMO,but you should be able to cast skills when you point to a player in the world.
It should be fixed in the PR#5 but maybe broken again in 6.05 so we need to see.
