### ISSUE TITLE
SmartCast not working with Astrologian Cards

### ISSUE THREAD

**Issue by WoefulMe** [akira0245/SmartCast#7]
First off, amazing plugin.
I've noticed that it does not work with drawn Astro cards, however.
Mouseover on character/nametag/party list not working for drawn cards - card defaults to player character as when a target isn't selected.
I have my play button on Q currently, but I figure this isn't the source of the issue.

Thanks!

**Comment by akira0245** [comment]
@wozaiha

**Comment by akira0245** [comment]
Sorry for the inconvenience. this feature is still in testing, it probably will be removed if there are too many issues with it. 
anyways smartcast is not designed to be a replacement for moaction.

**Comment by WoefulMe** [comment]
No worries! It already working for heals is very helpful, I was just bringing the cards to your attention in case they were intended to work, but didn't for some reason. Thanks for the hard work on this plugin!

**Comment by wozaiha** [comment]
It should be fixed now,Please tell if it still have problems.
