### ISSUE TITLE
Disable Field Mouseover

### ISSUE THREAD

**Issue by InitialDet** [akira0245/SmartCast#9]
Looks like theres not a option to disable the mouseover function? Sometimes i need to use vercure on myself but my mouse was hovering someone else and it doesnt target me.

I dont mind the UI mouse over in the party list, but the field mouseover is a problem.

**Comment by wozaiha** [comment]
It is now able to enable these two parts sepetately in the 6.08 fix version
Please tell me if there are any bugs.
